jguzdv/NuGet-Packages

.github/workflows/AspNetCore.DataProtection.yml, .github/workflows/AspNetCore.Logging.yml, NuGet-Packages.sln
=> Add more jobs

.github/workflows/JGUZDV.L10n.yml, NuGet-Packages.sln, libraries/JGUZDV.L10n/src/JGUZDV.L10n.csproj, libraries/JGUZDV.L10n/src/L10nString.cs, libraries/JGUZDV.L10n/src/L10nStringJsonConverter.cs, libraries/JGUZDV.L10n/test/JGUZDV.L10n.Tests.csproj, libraries/JGUZDV.L10n/test/L10nStringJsonConverterTest.cs, libraries/JGUZDV.L10n/test/L10nStringTests.cs
Default localization (L10n) model used in our applications
=> L10nStrings

libraries/JGUZDV.L10n/src/JGUZDV.L10n.csproj, libraries/JGUZDV.L10n/src/L10nString.cs, libraries/JGUZDV.L10n/src/L10nStringJsonConverter.cs, libraries/JGUZDV.L10n/test/L10nStringJsonConverterTest.cs, libraries/JGUZDV.L10n/test/L10nStringTests.cs
Unfortunately the namespace used was wrong.
=> L10n namespace

libraries/JGUZDV.Blazor.Components/samples/JGUZDV.Blazor.Components.Samples.csproj, libraries/JGUZDV.Blazor.Components/samples/Pages/ModalPage.razor, libraries/JGUZDV.Blazor.Components/src/JGUZDV.Blazor.Components.csproj, libraries/JGUZDV.Blazor.Components/src/Modals/Modal.razor
Fix a bug where an net8 optimization made the modal not rerendering its contents.
=> Bugfix for net8

libraries/JGUZDV.Blazor.Components/src/JGUZDV.Blazor.Components.csproj, libraries/JGUZDV.Blazor.Components/src/Modals/Modal.razor, libraries/JGUZDV.Blazor.Components/src/Modals/Modal.razor.css
=> Modal background blurred

libraries/JGUZDV.WebApiHost/src/Extensions/AuthorizationPolicyBuilderExtensions.cs, libraries/JGUZDV.WebApiHost/src/JGUZDV.WebApiHost.csproj, libraries/JGUZDV.WebApiHost/src/WebApiHost.cs
Scopes can be multi claim, single value or single claim, multi value (or probably a combination of both).
This PR takes care, it'll correctly check for the existence of scope.
=> Add check for allowed Scopes

NuGet-Packages.sln, libraries/JGUZDV.Blazor.Components.L10n/src/L10nViewer.razor, libraries/JGUZDV.Blazor.Components.L10n/src/L10nViewer.razor.css, libraries/JGUZDV.Blazor.Components/samples/Pages/Index.razor, libraries/JGUZDV.Blazor.Components/samples/Pages/L10nViewPage.razor
Added L10nViewer as a component
=> Added L10nViewer

libraries/JGUZDV.Blazor.Components/samples/Pages/DropdownPage.razor, libraries/JGUZDV.Blazor.Components/src/Inputs/DropdownSearch.razor, libraries/JGUZDV.Blazor.Components/src/JGUZDV.Blazor.Components.csproj
Added searchquery as parameter for searchdropdown
=> Added searchquery as parameter for searchdropdown

libraries/JGUZDV.DynamicForms/samples/JGUZDV.DynamicForms.Samples/JGUZDV.DynamicForms.Samples.Client/JGUZDV.DynamicForms.Samples.Client.csproj, libraries/JGUZDV.DynamicForms/samples/JGUZDV.DynamicForms.Samples/JGUZDV.DynamicForms.Samples.Client/Pages/FieldPage.razor, libraries/JGUZDV.DynamicForms/samples/JGUZDV.DynamicForms.Samples/JGUZDV.DynamicForms.Samples.Client/Pages/Home.razor, libraries/JGUZDV.DynamicForms/samples/JGUZDV.DynamicForms.Samples/JGUZDV.DynamicForms.Samples.Client/Program.cs, libraries/JGUZDV.DynamicForms/samples/JGUZDV.DynamicForms.Samples/JGUZDV.DynamicForms.Samples/Program.cs, libraries/JGUZDV.DynamicForms/src/JGUZDV.DynamicForms.Blazor/Component1.razor, libraries/JGUZDV.DynamicForms/src/JGUZDV.DynamicForms.Blazor/Component1.razor.css, libraries/JGUZDV.DynamicForms/src/JGUZDV.DynamicForms.Blazor/Constraints/EditConstraints.razor, libraries/JGUZDV.DynamicForms/src/JGUZDV.DynamicForms.Blazor/Constraints/SizeConstraintEdit.razor, libraries/JGUZDV.DynamicForms/src/JGUZDV.DynamicForms.Blazor/Fields/DefaultFieldInput.razor, libraries/JGUZDV.DynamicForms/src/JGUZDV.DynamicForms.Blazor/JGUZDV.DynamicForms.Blazor.csproj, libraries/JGUZDV.DynamicForms/src/JGUZDV.DynamicForms.Blazor/Resources/ComponentStrings.en.resx, libraries/JGUZDV.DynamicForms/src/JGUZDV.DynamicForms.Blazor/Resources/ComponentStrings.resx, libraries/JGUZDV.DynamicForms/src/JGUZDV.DynamicForms.Blazor/ValueConfigurationForm.razor, libraries/JGUZDV.DynamicForms/src/JGUZDV.DynamicForms.Extensions/FormField.cs, libraries/JGUZDV.DynamicForms/src/JGUZDV.DynamicForms.Extensions/JGUZDV.DynamicForms.Extensions.csproj, libraries/JGUZDV.DynamicForms/src/JGUZDV.DynamicForms/DynamicFormsConfiguration.cs, libraries/JGUZDV.DynamicForms/src/JGUZDV.DynamicForms/JGUZDV.DynamicForms.csproj, libraries/JGUZDV.DynamicForms/src/JGUZDV.DynamicForms/Model/FieldType.cs, libraries/JGUZDV.DynamicForms/src/JGUZDV.DynamicForms/Resources/Validations.en.resx, libraries/JGUZDV.DynamicForms/src/JGUZDV.DynamicForms/Resources/Validations.resx, libraries/JGUZDV.DynamicForms/src/JGUZDV.DynamicForms/Serialization/FieldConverter.cs, libraries/JGUZDV.DynamicForms/test/JGUZDV.DynamicForms.Tests/FieldTests.cs
=> add translations

libraries/JGUZDV.Extensions.OpenTelemetry/src/JGUZDV.Extensions.OpenTelemetry.csproj
=> Bumped Version

libraries/JGUZDV.JobHost/Directory.Build.props, libraries/JGUZDV.JobHost/src/JGUZDV.JobHost/samples/JGUZDV.JobHost.Sample/Program.cs, libraries/JGUZDV.JobHost/src/JGUZDV.JobHost/samples/JGUZDV.JobHost.Sample/SampleMeterContainer.cs, libraries/JGUZDV.JobHost/src/JGUZDV.JobHost/samples/JGUZDV.JobHost.Sample/appsettings.json, libraries/JGUZDV.JobHost/src/JGUZDV.JobHost/src/JGUZDV.JobHost.csproj, libraries/JGUZDV.JobHost/src/JGUZDV.JobHost/src/JobHost.cs, libraries/JGUZDV.JobHost/src/JGUZDV.JobHost/src/README.md
Using JDUZDV.Extensions.OpenTelemetry to add OpenTelemetry to JobHost.
=> Added OpenTelemetry extension method usage

libraries/JGUZDV.Extensions.OpenTelemetry/src/JGUZDV.Extensions.OpenTelemetry.csproj
Used version range for ms hosting package.
=> Merge  bugfix-ot-version-range into main

NuGet-Packages.sln, libraries/JGUZDV.Blazor.Components/samples/Shared/Pages/AppHeaderPage.razor, libraries/JGUZDV.Blazor.Components/samples/Web/Components/MainLayout.razor, libraries/JGUZDV.Blazor.Components/samples/WebAssembly/MainLayout.razor, libraries/JGUZDV.Blazor.Components/src/JGOO/AppHeader.razor, libraries/JGUZDV.Blazor.Components/src/JGOO/AppHeader.razor.css, libraries/JGUZDV.Blazor.Components/src/JGOO/Sidebar.razor, libraries/JGUZDV.Blazor.Components/src/JGOO/Sidebar.razor.css, libraries/JGUZDV.Blazor.Components/src/JGUZDV.Blazor.Components.csproj
added Navigationspecs to appheader and sidebar
=> added Navigationspecs to appheader and sidebar

libraries/JGUZDV.Blazor.Components/samples/Static/Components/Pages/Home.razor, libraries/JGUZDV.Blazor.Components/src/DarkModeSelector.razor, libraries/JGUZDV.Blazor.Components/src/Dropdown.razor, libraries/JGUZDV.Blazor.Components/src/Dropdown.razor.css, libraries/JGUZDV.Blazor.Components/src/JGOO/AppHeader.razor, libraries/JGUZDV.Blazor.Components/src/JGOO/AppHeader.razor.css, libraries/JGUZDV.Blazor.Components/src/JGOO/Sidebar.razor, libraries/JGUZDV.Blazor.Components/src/JGOO/Sidebar.razor.css, libraries/JGUZDV.Blazor.Components/src/JGUZDV.Blazor.Components.csproj, libraries/JGUZDV.Blazor.Components/src/Resources/ComponentStrings.en-US.resx, libraries/JGUZDV.Blazor.Components/src/Resources/ComponentStrings.resx, libraries/JGUZDV.Blazor.Components/src/ts/JGUZDV.Blazor.Components.lib.module.ts
Appheader impl of tab navigation and improvement of accesibility
=> Appheader impl of tab navigation and improvement of accesibility

libraries/JGUZDV.Blazor.Components/samples/Shared/Pages/DropdownPage.razor, libraries/JGUZDV.Blazor.Components/samples/Static/Components/Pages/Home.razor, libraries/JGUZDV.Blazor.Components/src/Dropdown.razor, libraries/JGUZDV.Blazor.Components/src/Dropdown.razor.css, libraries/JGUZDV.Blazor.Components/src/JGUZDV.Blazor.Components.csproj, libraries/JGUZDV.Blazor.Components/src/ts/JGUZDV.Blazor.Components.lib.module.ts
fixed bug so that dropdown toggle element works and also some static bla works
=> App header/bug fix dropdown

libraries/JGUZDV.Blazor.Components/src/Inputs/DropdownSearch.razor, libraries/JGUZDV.Blazor.Components/src/JGUZDV.Blazor.Components.csproj
Das Zurücksetzen des SearchQueries auf "" ist nun möglich.
=> Blazor components/dropdown search

libraries/JGUZDV.L10n/src/JGUZDV.L10n.csproj, libraries/JGUZDV.L10n/src/L10nString.cs
added a constructor for tuples für L10NString
=> added a constructor for tuples für L10NString

libraries/JGUZDV.L10n/src/JGUZDV.L10n.csproj, libraries/JGUZDV.L10n/src/L10nString.cs
Reverts jguzdv/NuGet-Packages#256
=> Revert "added a constructor for tuples für L10NString"

libraries/JGUZDV.DynamicForms/Directory.Build.props, libraries/JGUZDV.DynamicForms/samples/JGUZDV.DynamicForms.Samples/JGUZDV.DynamicForms.Samples.Client/Pages/FieldPage.razor, libraries/JGUZDV.DynamicForms/src/JGUZDV.DynamicForms.Blazor/FieldComponents/DefaultFieldInput.razor, libraries/JGUZDV.DynamicForms/src/JGUZDV.DynamicForms/Model/Field.cs, libraries/JGUZDV.DynamicForms/src/JGUZDV.DynamicForms/Model/FieldType.cs
=> validate choices

libraries/JGUZDV.Blazor.Components/samples/Web.Client/MainLayout.razor, libraries/JGUZDV.Blazor.Components/samples/Web.Client/Routes.razor, libraries/JGUZDV.Blazor.Components/samples/Web/Components/App.razor, libraries/JGUZDV.Blazor.Components/src/JGUZDV.Blazor.Components.csproj, libraries/JGUZDV.Blazor.Components/src/ts/JGUZDV.Blazor.Components.lib.module.ts, libraries/JGUZDV.Blazor.Components/src/wwwroot/JGUZDV.Blazor.Components.lib.module.js
JGUZDV.Blazor.Components.lib.module.ts and .js by
targeting the entire component for button clicks.
=> Improved event handling in
